name: binder-env
channels:
  - pyPI
dependencies:
  - python=3.11
  - debiased_spatial_whittle
  - ipywidgets
  - matplotlib
  - ipympl
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
